// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      _ref = AppView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppView.prototype.template = _.template('\
    <button class="hit-button">Hit</button> <button class="stand-button">Stand</button>\
    <div class="player-hand-container"></div>\
    <div class="dealer-hand-container"></div>\
  ');

    AppView.prototype.events = {
      "click .hit-button": function() {
        return this.model.get('playerHand').hit();
      },
      "click .stand-button": function() {
        return this.model.get('dealerHand').stand();
      }
    };

    AppView.prototype.initialize = function() {
      var _this = this;

      this.render();
      this.model.get('dealerHand').on('stand', function() {
        _this.model.get('dealerHand').models[0].flip();
        while (_this.model.get('dealerHand').scores()[0] < 17) {
          _this.model.get('dealerHand').hit();
        }
        if (_this.model.get('dealerHand').scores()[0] > 21) {
          return _this.model.get('dealerHand').bust();
        } else if (_this.model.get('dealerHand').scores()[0] < _this.model.get('playerHand').scores()[0]) {
          return _this.model.get('dealerHand').bust();
        } else {
          return _this.model.get('playerHand').bust();
        }
      });
      this.model.get('playerHand').on('hit', function() {
        if (_this.model.get('playerHand').scores()[0] > 21) {
          return _this.model.get('playerHand').bust();
        }
      });
      this.model.get('playerHand').on('bust', function() {
        console.log("BUST HAS BEEN HEARD!");
        _this.model.reDeal();
        return console.log(_this);
      });
      return this.model.get('dealerHand').on('bust', function() {
        return _this.model.reDeal();
      });
    };

    AppView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.$('.player-hand-container').html(new HandView({
        collection: this.model.get('playerHand')
      }).el);
      return this.$('.dealer-hand-container').html(new HandView({
        collection: this.model.get('dealerHand')
      }).el);
    };

    return AppView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=AppView.map
*/
